
import { mainnet, sepolia } from "viem/chains"

const PLOT_VERSION = 0
const EDITOR_VERSION = "1.0"
const MAIN_VERSION = "1.0"

const ALLOWED_ORIGINS = "*"
const CACHE_PURGE_ORIGIN = "https://trraform.com"
const PLOT_DATA_BUCKET_URL = "https://plots.trraform.com"
const TOKEN_METADATA_BUCKET_URL = "https://token-metadata.trraform.com"
const IMAGES_BUCKET_URL = "https://images.trraform.com"

const CHAIN = sepolia
const DATA_CONTRACT_ADDRESS = "0x07Fa34D793c121Db560f406F61a04d6D1E81f2F7"
const WRAPPER_CONTRACT_ADDRESS = "0xE057325a08bdf3FC9138A76c106dE48dEe684c81"
const D0_MINT_PRICE = 0.001
const MIN_SMP = 0.0001
const MAX_SMP = 9999
const TEMP_LOCK_MINT_PRICE = 0.005
const MAX_DEPTH = 2
const DEFAULT_SMP = 0.001
const D0_PLOT_COUNT = 34998
const PLOT_COUNT = 24

const MAX_BUILD_SIZES = [32, 48, 64]
const LOW_RES = 2 //low res build dimensions
const CHUNK_SIZE = 8

const NAME_FIELD_MAXLEN = 30
const DESC_FIELD_MAXLEN = 128
const LINK_FIELD_MAXLEN = 128
const LINK_LABEL_FIELD_MAXLEN = 64

const REPORT_PLOT_MSG_MINLEN = 250
const REPORT_PLOT_MSG_MAXLEN = 500

const FIND_OPEN_PLOTS_COUNT = 100

export { CHAIN, EDITOR_VERSION, MAIN_VERSION, PLOT_VERSION, PLOT_DATA_BUCKET_URL, TOKEN_METADATA_BUCKET_URL, IMAGES_BUCKET_URL, CACHE_PURGE_ORIGIN, DATA_CONTRACT_ADDRESS, WRAPPER_CONTRACT_ADDRESS, D0_MINT_PRICE, MIN_SMP, MAX_SMP, TEMP_LOCK_MINT_PRICE, MAX_DEPTH, DEFAULT_SMP, PLOT_COUNT, D0_PLOT_COUNT, MAX_BUILD_SIZES, NAME_FIELD_MAXLEN, DESC_FIELD_MAXLEN, LINK_FIELD_MAXLEN, LINK_LABEL_FIELD_MAXLEN, LOW_RES, CHUNK_SIZE, REPORT_PLOT_MSG_MINLEN, REPORT_PLOT_MSG_MAXLEN, ALLOWED_ORIGINS, FIND_OPEN_PLOTS_COUNT }
