
const PLOT_VERSION = 0
const EDITOR_VERSION = "1.0"
const MAIN_VERSION = "1.0"

const PLOT_DATA_BUCKET_URL = "https://plots.trraform.com"
const IMAGES_BUCKET_URL = "https://images.trraform.com"

const MAX_DEPTH = 2
const D0_PLOT_COUNT = 34998
const PLOT_COUNT = 24

const MAX_BUILD_SIZES = [32, 48, 64]
const MIN_BUILD_SIZE = 6
const LOW_RES = 2 //low res build dimensions
const CHUNK_SIZE = 8

const NAME_FIELD_MAXLEN = 30
const DESC_FIELD_MAXLEN = 128
const LINK_FIELD_MAXLEN = 128
const LINK_LABEL_FIELD_MAXLEN = 64

const REPORT_PLOT_MSG_MINLEN = 250
const REPORT_PLOT_MSG_MAXLEN = 500

const FIND_OPEN_PLOTS_COUNT = 100

export { EDITOR_VERSION, MAIN_VERSION, PLOT_VERSION, PLOT_DATA_BUCKET_URL, IMAGES_BUCKET_URL, MAX_DEPTH, PLOT_COUNT, D0_PLOT_COUNT, MIN_BUILD_SIZE, MAX_BUILD_SIZES, NAME_FIELD_MAXLEN, DESC_FIELD_MAXLEN, LINK_FIELD_MAXLEN, LINK_LABEL_FIELD_MAXLEN, LOW_RES, CHUNK_SIZE, REPORT_PLOT_MSG_MINLEN, REPORT_PLOT_MSG_MAXLEN, FIND_OPEN_PLOTS_COUNT }
