
const PLOT_VERSION = 0
const EDITOR_VERSION = "1.0"
const MAIN_VERSION = "1.0"

const ALLOWED_ORIGINS = "*"
const CACHE_PURGE_ORIGIN = "https://trraform.com"
const PLOT_DATA_BUCKET_URL = "https://plots.trraform.com"
const TOKEN_METADATA_BUCKET_URL = "https://token-metadata.trraform.com"
const IMAGES_BUCKET_URL = "https://images.trraform.com"

const IMAGE_FILE_EXT = "png"

const DATA_CONTRACT_ADDRESS = "0x72aF9c87073a9ea433eeF058961bE5CF09C20117"
const WRAPPER_CONTRACT_ADDRESS = "0x023aCd02AF1783471895fcf281dEfd8ca6eF04e2"

const D0_MINT_PRICE = 0.001
const MIN_SMP = 0.0001
const MAX_SMP = 9999
const TEMP_LOCK_MINT_PRICE = 0.005
const MAX_DEPTH = 2
const DEFAULT_SMP = 0.001
const D0_PLOT_COUNT = 50000
const PLOT_COUNT = 24

const MAX_BUILD_SIZES = [32, 48, 64]
const LOW_RES = 4 //low res build dimensions
const CHUNK_SIZE = 8

const NAME_FIELD_MAXLEN = 30
const DESC_FIELD_MAXLEN = 128
const LINK_FIELD_MAXLEN = 128
const LINK_LABEL_FIELD_MAXLEN = 64

const REPORT_PLOT_MSG_MINLEN = 250
const REPORT_PLOT_MSG_MAXLEN = 500

export { EDITOR_VERSION, MAIN_VERSION, PLOT_VERSION, PLOT_DATA_BUCKET_URL, TOKEN_METADATA_BUCKET_URL, IMAGES_BUCKET_URL, CACHE_PURGE_ORIGIN, IMAGE_FILE_EXT, DATA_CONTRACT_ADDRESS, WRAPPER_CONTRACT_ADDRESS, D0_MINT_PRICE, MIN_SMP, MAX_SMP, TEMP_LOCK_MINT_PRICE, MAX_DEPTH, DEFAULT_SMP, PLOT_COUNT, D0_PLOT_COUNT, MAX_BUILD_SIZES, NAME_FIELD_MAXLEN, DESC_FIELD_MAXLEN, LINK_FIELD_MAXLEN, LINK_LABEL_FIELD_MAXLEN, LOW_RES, CHUNK_SIZE, REPORT_PLOT_MSG_MINLEN, REPORT_PLOT_MSG_MAXLEN, ALLOWED_ORIGINS }
